### ISSUE TITLE
unable to parse directory volume name

### ISSUE THREAD

**Issue by hamimistimewa** [chris2k20/proxmox-cloud-init#1]
Hi

I'm having trouble starting the VM it seems cloud-init isn't stored on any disk, cmiiw.

```
root@hamim-lab-01:~# qm set 101 --cicustom "user=local:cloud-init/101-cloud-init.yml"
update VM 101: -cicustom user=local:cloud-init/101-cloud-init.yml
root@hamim-lab-01:~#
root@hamim-lab-01:~# qm start 101
unable to parse directory volume name 'cloud-init/101-cloud-init.yml'
root@hamim-lab-01:~#
```

But, in the Hardware menu cloud-init there is already an internal disk, attached.

![image](https://user-images.githubusercontent.com/37973020/170080300-564d235a-d6cf-4ecc-a8ad-9da9069f2465.png)

Please advise what can I do?

Thank you.

Hamim

**Comment by chris2k20** [comment]
Hey Hamim, 

which image are you using inside of your VM?

Did you try that ubuntu 20.04 with cloud init? See https://gist.github.com/chris2k20/dba14515071bd5a14e48cf8b61f7d2e2

Best regards, 
Chris
